# Generated by Django 4.2.6 on 2023-10-28 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migratoryworker',
            name='employer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_employer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_workers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='migratoryworker',
            name='police',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_police': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police_workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
