# Generated by Django 4.2.5 on 2024-04-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsubmission',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobsubmission',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobsubmission',
            name='work_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], max_length=20),
        ),
    ]
