# Generated by Django 4.2.6 on 2023-10-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_migratoryworker_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migratoryworker',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
