# Generated by Django 4.2.5 on 2024-04-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_bookingworkers_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubmission',
            name='is_booked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
