# Generated by Django 4.2.6 on 2023-11-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_workcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='migratoryworker',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.workcategory'),
        ),
    ]
