# Generated by Django 4.2.6 on 2023-11-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_migratoryworker_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
