# Generated by Django 4.2.6 on 2023-11-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userprofile_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
