# Generated by Django 4.2.5 on 2023-11-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_police'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migratoryworker',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='migratoryworker',
            name='adhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='migratoryworker',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='police',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
    ]
