# Generated by Django 4.2.5 on 2023-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_migratoryworker_work_permit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migratoryworker',
            name='work_permit',
        ),
        migrations.AddField(
            model_name='migratoryworker',
            name='work_permit_verified',
            field=models.BooleanField(default=False),
        ),
    ]
