# Generated by Django 4.2.5 on 2023-11-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_bookingworker_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.migratoryworker'),
        ),
    ]
