# Generated by Django 4.2.5 on 2024-02-07 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_payment_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance')], max_length=20)),
                ('work_location', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Duration in months')),
                ('qualification_required', models.CharField(choices=[('High School', 'High School'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_jobs_as_agent', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_jobs_as_employer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Submission',
                'verbose_name_plural': 'Job Submissions',
            },
        ),
    ]
