# Generated by Django 4.2.5 on 2024-02-07 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_jobsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsubmission',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobsubmission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobsubmission',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='jobsubmission',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_jobs_as_agent', to='home.workcategory'),
        ),
    ]
