# Generated by Django 4.2.5 on 2024-02-07 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_jobsubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsubmission',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_jobs_as_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
