# Generated by Django 4.2.5 on 2024-02-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_jobsubmission_agent_jobsubmission_worker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsubmission',
            name='description',
        ),
    ]
