# Generated by Django 4.2.5 on 2024-02-17 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_jobsubmission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsubmission',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
