# Generated by Django 4.2.5 on 2024-02-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_jobsubmission_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubmission',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
