# Generated by Django 4.2.5 on 2024-02-18 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_jobsubmission_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsubmission',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.workcategory'),
        ),
    ]
