# Generated by Django 4.2.5 on 2024-02-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_jobsubmission_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsubmission',
            old_name='title',
            new_name='category',
        ),
    ]
