# Generated by Django 4.2.5 on 2024-02-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_title_jobsubmission_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsubmission',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobsubmission',
            name='worker',
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
