# Generated by Django 4.2.5 on 2024-02-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_salarypayment_worker_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
