# Generated by Django 4.2.5 on 2024-03-01 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_salarypayment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='worker',
        ),
        migrations.DeleteModel(
            name='BookingWorker',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
