# Generated by Django 4.2.5 on 2024-02-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_bookingworker_title_bookingworker_work_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingworker',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bookingworker',
            name='work_location',
        ),
    ]
