# Generated by Django 4.2.5 on 2024-03-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_bookingworkers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsubmission',
            name='title',
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.workcategory'),
        ),
    ]
