# Generated by Django 4.2.5 on 2024-02-28 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_bookingworker_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingworker',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bookingworker',
            name='date_accepted',
        ),
        migrations.RemoveField(
            model_name='bookingworker',
            name='date_declined',
        ),
        migrations.RemoveField(
            model_name='bookingworker',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='bookingworker',
            name='duration_unit',
        ),
        migrations.RemoveField(
            model_name='bookingworker',
            name='is_work_completed',
        ),
        migrations.RemoveField(
            model_name='bookingworker',
            name='status',
        ),
        migrations.AddField(
            model_name='bookingworker',
            name='job_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_workers', to='home.jobsubmission'),
        ),
    ]
