# Generated by Django 4.2.5 on 2024-02-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_bookingworker_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingworker',
            old_name='job_submission',
            new_name='title',
        ),
    ]
