# Generated by Django 4.2.5 on 2024-03-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_jobsubmission_title_jobsubmission_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsubmission',
            old_name='category',
            new_name='title',
        ),
    ]
