# Generated by Django 4.2.5 on 2024-03-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_rename_category_jobsubmission_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='migratoryworker',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
